### ISSUE TITLE
JSONDecode Error 

### ISSUE THREAD

**Issue by fw-nytra** [Coderhypo/outline-importer#2]
Hi, thanks for your effort creating a markdown importer for outline. 
I was wondering if something in a new version has broken your importer.
When running I get the following error. 

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\outline-importer\cli.py", line 35, in <module>
    cli.run()
  File "C:\Users\User\outline-importer\cli.py", line 30, in run
    importer.run()
  File "C:\Users\User\outline-importer\importer\__init__.py", line 21, in run
    self._import_collection(c)
  File "C:\Users\User\outline-importer\importer\__init__.py", line 25, in _import_collection
    cid = self.api_server.create_collection(collection)
  File "C:\Users\User\outline-importer\importer\client.py", line 74, in create_collection
    return self.http_client.create_collection(
  File "C:\Users\User\outline-importer\importer\client.py", line 43, in create_collection
    collection = rsp.json()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by hyponet** [comment]
apologize for reply late, I build a test environment as version below:
python: 3.7.2
outline: 0.62.0

but I cannot reproduce this, would you like to provide more information, such as python or outline version?

**Comment by fw-nytra** [comment]
No problem, thank you for answering at all!
I tried using your suggested python version and outline: 0.65.2 and the upload does work perfect! 
I only have a problem with special characters like äöü which are not converted correctly.
Geschäftsführung gets GeschÃ¤ftsfÃ¼hrung 
Do you have any idea how to solve this ? Maybe its a problem with utf8 format.
